### ISSUE TITLE
About the Judging Programme

### ISSUE THREAD

**Issue by RootCui** [XtherDevTeam/zqhf-oj#1]
It has been a long time since I last visited your OJ. Here are some questions. Hope 您 can give a short explanation or answer to these questions if 您 have a lot of free time that's enough to answer them.
1. How does the judging programme work? Will it work well if there is a programme with an endless loop? Will the history records affect its running?
2. Is the closing of OJ caused by something wrong about the judging programme?
3. Does the judging program take most of the resources of CPU and memory?
4. If a programme takes a lot of memory to run, which programme will killed by the system, the judging programme or the submission, or both of them?
5. If the judging programme has already fixed and can be used to judge the submissions, will your OJ work well, at least can be used without considering the reasons of time or memory limits?
6. 
In the end, hope you can have a great result of the final exam and a enjoyable life! XD

**Comment by xiaokang00010** [comment]
1. answer
    (1) It's hard to say. You can checkout `judge/judgeServer.py` for more details
    (2) JudgeServer will wait for the specified time.It will **stop** the sub-process during the timeout
2. answer
    (1) No. The reason for closing my server is **"My public IP changed, and i can't change it when i'm in school"**
3. answer
    (1) No. It used flask for framework, flask is a lightly framework.
4. answer 
    (1) It will killed by linux itself
5. answer
    (1) Of course.

Enjoy yourself :- )
